services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: habitfer
      MYSQL_USER: habitfer
      MYSQL_PASSWORD: habitfer
    ports:
      - "3308:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
