import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outPath = path.join(__dirname, "../src/data/frases_motivacionales.json");
const srcPath = outPath;

const REPETITIVE =
  /(se fortalece|se construye|crece) cuando nadie mira|verdadera victoria/i;

/** Frases originales y citas reales / parafraseadas con variedad de estilo */
const CURATED = [
  { frase: "No controles el mundo; controla la forma en que respondes a el.", autor: "Epicteto" },
  { frase: "Un dia bien vivido pesa mas que cien promesas vacias.", autor: "Seneca" },
  { frase: "La incomodidad de hoy puede ser la libertad de manana.", autor: "Entrenador personal" },
  { frase: "Hazlo cansado, hazlo con miedo, hazlo imperfecto; pero hazlo.", autor: "Coach de disciplina" },
  { frase: "Tu caracter se escribe en los momentos donde podrias abandonar.", autor: "Marco Aurelio" },
  { frase: "Cada repeticion es un voto silencioso por la persona que quieres ser.", autor: "James Clear" },
  { frase: "La mente que aprende a esperar tambien aprende a vencer.", autor: "Ferstein" },
  { frase: "No necesitas motivacion eterna; necesitas una decision firme.", autor: "Preparador fisico" },
  { frase: "Lo que toleras en tu rutina decide lo que recibes en tu vida.", autor: "Coach de habitos" },
  { frase: "La paz no llega cuando todo se ordena; llega cuando tu te ordenas.", autor: "Marco Aurelio" },
  { frase: "Que se de dedo, que se de dedo.", autor: "Jhova de aquino" },

  { frase: "No es lo que te ocurre, sino como reaccionas a ello.", autor: "Epicteto" },
  { frase: "Sufrimos mas en la imaginacion que en la realidad.", autor: "Seneca" },
  { frase: "La felicidad de tu vida depende de la calidad de tus pensamientos.", autor: "Marco Aurelio" },
  { frase: "Primero dite quien quieres ser y luego haz lo que debas.", autor: "Epicteto" },
  { frase: "No recibas con fastidio lo que ocurre; acéptalo.", autor: "Marco Aurelio" },
  { frase: "El destino guia al que lo acepta y arrastra al que se resiste.", autor: "Seneca" },
  { frase: "Mientras tardamos en deliberar, suelen pasar cosas peores.", autor: "Caton el Joven" },
  { frase: "No pidas que las cosas sean faciles; pide ser mas fuerte.", autor: "Inspirado en Epicteto" },
  { frase: "Quien teme a la muerte nunca hara nada digno de un hombre vivo.", autor: "Seneca" },
  { frase: "La suerte es lo que ocurre cuando la preparacion encuentra la oportunidad.", autor: "Seneca" },
  { frase: "El impedimento a la accion hace avanzar la accion. Lo que se interpone se convierte en el camino.", autor: "Marco Aurelio" },
  { frase: "Si buscas la paz, no busques fuera; buscala en ti.", autor: "Marco Aurelio" },
  { frase: "No desperdicies el resto de tu vida en pensamientos sobre otros.", autor: "Marco Aurelio" },
  { frase: "El alma se tiñe del color de sus pensamientos.", autor: "Marco Aurelio" },
  { frase: "Haz cada acto de tu vida como si fuera el ultimo.", autor: "Marco Aurelio" },
  { frase: "La mejor venganza es no ser como tu enemigo.", autor: "Marco Aurelio" },
  { frase: "No pierdas mas tiempo discutiendo como debe ser un buen hombre. Se uno.", autor: "Marco Aurelio" },
  { frase: "No actues como si fueras a vivir diez mil anos. La muerte pende de ti.", autor: "Marco Aurelio" },
  { frase: "La riqueza consiste en no tener necesidades, no en tener mucho.", autor: "Seneca" },
  { frase: "El fuego prueba el oro; la adversidad prueba a los hombres fuertes.", autor: "Seneca" },
  { frase: "Dificultades fortalecen la mente, asi como el trabajo fortalece el cuerpo.", autor: "Seneca" },
  { frase: "Comienza a vivir inmediatamente y cuenta cada dia como una vida aparte.", autor: "Seneca" },
  { frase: "No hay viento favorable para quien no sabe a que puerto va.", autor: "Seneca" },
  { frase: "El hombre que sufre antes de que sea necesario sufre mas de lo necesario.", autor: "Seneca" },
  { frase: "El tiempo descubre la verdad.", autor: "Seneca" },
  { frase: "Donde hay un humano, hay una oportunidad para la amistad.", autor: "Seneca" },
  { frase: "La vida es larga si sabes usarla.", autor: "Seneca" },
  { frase: "No es que tengamos poco tiempo, sino que perdemos mucho.", autor: "Seneca" },
  { frase: "Elige un maestro cuya vida, palabra y mente te sirvan de modelo.", autor: "Seneca" },
  { frase: "Solo hay un camino hacia la felicidad: dejar de aferrarse a lo que esta fuera de tu control.", autor: "Epicteto" },
  { frase: "Ninguna gran cosa se crea de repente.", autor: "Epicteto" },
  { frase: "No busques que los acontecimientos sucedan como quieres. Quierelos como suceden.", autor: "Epicteto" },
  { frase: "La libertad es la unica meta digna. Solo es libre quien vive como quiere.", autor: "Epicteto" },
  { frase: "Si quieres mejorar, acepta que te consideren tonto y superficial.", autor: "Epicteto" },
  { frase: "El que dice que puede y el que dice que no puede, suelen tener razon.", autor: "Henry Ford" },
  { frase: "El unico modo de hacer un gran trabajo es amar lo que haces.", autor: "Steve Jobs" },
  { frase: "No cuentes los dias; haz que los dias cuenten.", autor: "Muhammad Ali" },
  { frase: "Yo no fallo. Aprendo.", autor: "Michael Jordan" },
  { frase: "El dolor es temporal; rendirse dura para siempre.", autor: "Lance Armstrong" },
  { frase: "La diferencia entre lo imposible y lo posible esta en la determinacion.", autor: "Tommy Lasorda" },
  { frase: "El exito no es definitivo, el fracaso no es fatal: lo que cuenta es el valor de seguir.", autor: "Winston Churchill" },
  { frase: "No mires el reloj; haz lo que hace el reloj. Sigue adelante.", autor: "Sam Levenson" },
  { frase: "La unica persona que estas destinado a ser eres tu mismo.", autor: "Ralph Waldo Emerson" },
  { frase: "Cree que puedes y ya estas a mitad de camino.", autor: "Theodore Roosevelt" },
  { frase: "La mejor forma de predecir el futuro es crearlo.", autor: "Peter Drucker" },
  { frase: "Actua como si lo que haces marcara la diferencia. La marca.", autor: "William James" },
  { frase: "El secreto de salir adelante es empezar.", autor: "Mark Twain" },
  { frase: "No esperes. El momento perfecto nunca llegara.", autor: "Napoleon Hill" },
  { frase: "La disciplina es el puente entre metas y logros.", autor: "Jim Rohn" },
  { frase: "Los habitos son la gravedad de la vida.", autor: "James Clear" },
  { frase: "Pequenos cambios, resultados notables.", autor: "James Clear" },
  { frase: "No te elevas al nivel de tus metas; caes al nivel de tus sistemas.", autor: "James Clear" },
  { frase: "La motivacion te pone en marcha; el habito te mantiene en el camino.", autor: "Jim Ryun" },
  { frase: "La excelencia no es un acto, sino un habito.", autor: "Aristoteles" },
  { frase: "Somos lo que hacemos repetidamente.", autor: "Aristoteles" },
  { frase: "El que domina a los demas es fuerte; el que se domina a si mismo es poderoso.", autor: "Lao Tse" },
  { frase: "Un viaje de mil millas comienza con un solo paso.", autor: "Lao Tse" },
  { frase: "El agua perfora la roca no por su fuerza, sino por su constancia.", autor: "Proverbio japones" },
  { frase: "Cae siete veces, levantate ocho.", autor: "Proverbio japones" },
  { frase: "Quien domina el amanecer domina el dia.", autor: "Proverbio" },
  { frase: "El hierro se templa con el fuego; el caracter con la dificultad.", autor: "Proverbio chino" },
  { frase: "Un arbol fuerte crece con vientos fuertes.", autor: "Proverbio japones" },
  { frase: "La paciencia es amarga, pero su fruto es dulce.", autor: "Jean-Jacques Rousseau" },
  { frase: "La constancia es la virtud por la que todas las demas dan fruto.", autor: "Voltaire" },
  { frase: "El genio es un uno por ciento de inspiracion y noventa y nueve de transpiracion.", autor: "Thomas Edison" },
  { frase: "No he fracasado; he encontrado diez mil formas que no funcionan.", autor: "Thomas Edison" },
  { frase: "La vida se encoge o se expande en proporcion al coraje de uno.", autor: "Anais Nin" },
  { frase: "Haz hoy lo que otros no quieren; manana viviras como otros no pueden.", autor: "Jerry Rice" },
  { frase: "Entrenar es celebrar lo que tu cuerpo puede hacer, no castigarlo por lo que comiste.", autor: "Coach de fitness" },
  { frase: "El sudor de hoy es la confianza de manana.", autor: "Entrenador personal" },
  { frase: "Una mala serie no define tu carrera; tu respuesta si.", autor: "Coach de fuerza" },
  { frase: "Levanta pesado hoy para que la vida no te pese manana.", autor: "Coach de fuerza" },
  { frase: "El progreso, no la perfeccion.", autor: "Coach de habitos" },
  { frase: "Un habito omitido es una oportunidad perdida de votar por quien quieres ser.", autor: "James Clear" },
  { frase: "La identidad cambia antes que el comportamiento: primero cree, luego actua.", autor: "James Clear" },
  { frase: "Hazlo tan facil que sea mas dificil no hacerlo.", autor: "James Clear" },
  { frase: "El entorno vence a la fuerza de voluntad casi siempre.", autor: "James Clear" },
  { frase: "La claridad vence a la motivacion.", autor: "James Clear" },
  { frase: "Empieza ridiculamente pequeno; escala despacio.", autor: "BJ Fogg" },
  { frase: "Celebra cada victoria pequena; tu cerebro necesita la senal.", autor: "BJ Fogg" },
  { frase: "Anclar un habito nuevo a uno viejo multiplica tus chances.", autor: "BJ Fogg" },
  { frase: "La manana es cuando escribes el guion del dia.", autor: "Coach de productividad" },
  { frase: "Ganar la manana no garantiza el dia, pero lo inclina a tu favor.", autor: "Coach de productividad" },
  { frase: "Duerme bien: es el habito que hace posible todos los demas.", autor: "Coach de salud" },
  { frase: "Bebe agua antes de cafe; tu cuerpo lleva horas en ayunas.", autor: "Coach de salud" },
  { frase: "Caminar diez minutos cuenta mas que planear una hora de gym.", autor: "Coach de salud" },
  { frase: "Lee diez paginas hoy; son mas de tres mil al ano.", autor: "Coach de aprendizaje" },
  { frase: "Aprender un poco cada dia supera a estudiar mucho de vez en cuando.", autor: "Coach de aprendizaje" },
  { frase: "La lectura es entrenamiento para la mente.", autor: "Coach de aprendizaje" },
  { frase: "Escribe tres lineas de gratitud; cambia el filtro del dia.", autor: "Coach de bienestar" },
  { frase: "Meditar cinco minutos no te hace monje; te hace mas presente.", autor: "Coach de bienestar" },
  { frase: "Respira antes de responder; la pausa es poder.", autor: "Coach de mindfulness" },
  { frase: "Tu atencion es tu activo mas valioso; protegela.", autor: "Cal Newport" },
  { frase: "El trabajo profundo crea valor; el trabajo superficial lo consume.", autor: "Cal Newport" },
  { frase: "Di no a lo bueno para decir si a lo excelente.", autor: "Stephen Covey" },
  { frase: "Empieza con el fin en mente.", autor: "Stephen Covey" },
  { frase: "Lo urgente rara vez es lo importante.", autor: "Dwight Eisenhower" },
  { frase: "Si no mides, no mejoras.", autor: "Peter Drucker" },
  { frase: "Lo que se mide se gestiona.", autor: "Peter Drucker" },
  { frase: "Un objetivo sin plan es solo un deseo.", autor: "Antoine de Saint-Exupery" },
  { frase: "Divide la montana en piedras pequenas.", autor: "Coach de metas" },
  { frase: "Un paso feo sigue siendo un paso adelante.", autor: "Coach de metas" },
  { frase: "El perfeccionismo es procrastinacion con disfraz elegante.", autor: "Coach de metas" },
  { frase: "Hecho es mejor que perfecto.", autor: "Sheryl Sandberg" },
  { frase: "La accion cura el miedo.", autor: "Coach de accion" },
  { frase: "El miedo pierde fuerza cuando lo nombras.", autor: "Coach de accion" },
  { frase: "Cuenta hasta cinco y muevete antes de que la mente te frene.", autor: "Mel Robbins" },
  { frase: "Tu yo futuro te esta viendo; no lo defraudes por comodidad.", autor: "Coach de disciplina" },
  { frase: "La comodidad es el enemigo silencioso del crecimiento.", autor: "Coach de disciplina" },
  { frase: "El aburrimiento es parte del proceso; no lo confundas con fracaso.", autor: "Coach de habitos" },
  { frase: "La repeticion aburre al ego pero construye al experto.", autor: "Coach de habitos" },
  { frase: "Confia en el proceso cuando los resultados tardan.", autor: "Coach de habitos" },
  { frase: "La racha no es suerte; es evidencia.", autor: "Coach de habitos" },
  { frase: "Romper la racha duele; usarlo como leccion duele menos que rendirte.", autor: "Coach de habitos" },
  { frase: "Vuelve al habito manana; nunca esperes al lunes.", autor: "Coach de habitos" },
  { frase: "Dos dias seguidos sin fallar es el inicio de una racha real.", autor: "Coach de habitos" },
  { frase: "Treinta dias crean un cambio visible; noventa lo hacen parte de ti.", autor: "Coach de habitos" },
  { frase: "Tu version de manana agradece lo que haces hoy cansado.", autor: "Coach de fuerza" },
  { frase: "El gimnasio vacio a las seis de la manana tiene mas disciplina que el lleno a las seis de la tarde.", autor: "Coach de fuerza" },
  { frase: "No busques motivacion; busca compromiso.", autor: "Coach de fuerza" },
  { frase: "La barra no miente; tu constancia tampoco deberia.", autor: "Coach de fuerza" },
  { frase: "Un PR pequeno sigue siendo progreso.", autor: "Coach de fuerza" },
  { frase: "Entrena la tecnica antes que el ego.", autor: "Coach de fuerza" },
  { frase: "Descansa cuando toca; descansar tambien es entrenar.", autor: "Coach de fuerza" },
  { frase: "La proteina no construye musculo; la constancia con la proteina si.", autor: "Nutricionista deportivo" },
  { frase: "Comer bien un dia no compensa comer mal toda la semana.", autor: "Nutricionista deportivo" },
  { frase: "Planifica la comida como planificas el entrenamiento.", autor: "Nutricionista deportivo" },
  { frase: "El hambre emocional pasa; el habito alimenticio queda.", autor: "Nutricionista deportivo" },
  { frase: "Analizar sin ejecutar es entretenimiento disfrazado de trabajo.", autor: "Emprendedor" },
  { frase: "Una hora enfocado supera ocho horas distraido.", autor: "Cal Newport" },
  { frase: "Apaga notificaciones; enciende resultados.", autor: "Coach de productividad" },
  { frase: "Tu telefono es herramienta o ancla; tu decides cada vez que lo desbloqueas.", autor: "Coach de productividad" },
  { frase: "La procrastinacion es el interes que pagas por no decidir.", autor: "Coach de productividad" },
  { frase: "Empieza con dos minutos; el resto suele seguir.", autor: "James Clear" },
  { frase: "Prepara el entorno la noche anterior; regalate una victoria temprana.", autor: "Coach de habitos" },
  { frase: "La ropa de entrenar lista es media batalla ganada.", autor: "Coach de habitos" },
  { frase: "Pon el libro sobre la almohada si quieres leer mas.", autor: "James Clear" },
  { frase: "Quita la app que te roba tiempo; no confies solo en fuerza de voluntad.", autor: "James Clear" },
  { frase: "Rodéate de quienes ya viven como quieres vivir.", autor: "Jim Rohn" },
  { frase: "Eres el promedio de las cinco personas con las que pasas mas tiempo.", autor: "Jim Rohn" },
  { frase: "La disciplina es elegir entre lo que quieres ahora y lo que quieres mas.", autor: "Abraham Lincoln" },
  { frase: "El caracter es lo que haces cuando nadie te mira.", autor: "John Wooden" },
  { frase: "Hazlo bien o no lo hagas.", autor: "John Wooden" },
  { frase: "El esfuerzo y la actitud son cosas que controlas.", autor: "John Wooden" },
  { frase: "Gana cada dia.", autor: "John Wooden" },
  { frase: "La preparacion es la clave del exito.", autor: "Alexander Graham Bell" },
  { frase: "La fortuna favorece a los audaces.", autor: "Virgilio" },
  { frase: "Audacia, audacia y siempre audacia.", autor: "Georges Danton" },
  { frase: "El coraje no es ausencia de miedo; es avanzar con el.", autor: "Nelson Mandela" },
  { frase: "Parece imposible hasta que se hace.", autor: "Nelson Mandela" },
  { frase: "La educacion es el arma mas poderosa para cambiar el mundo.", autor: "Nelson Mandela" },
  { frase: "La vida se comprime o se expande segun tu coraje.", autor: "Anais Nin" },
  { frase: "No dejes que el miedo a perder sea mayor que la emocion de ganar.", autor: "Robert Kiyosaki" },
  { frase: "Invertir en ti mismo paga el mejor interes.", autor: "Benjamin Franklin" },
  { frase: "Una inversion en conocimiento paga los mejores dividendos.", autor: "Benjamin Franklin" },
  { frase: "Temprano a la cama y temprano a levantarse hace saludable, rico y sabio.", autor: "Benjamin Franklin" },
  { frase: "Bien hecho es mejor que bien dicho.", autor: "Benjamin Franklin" },
  { frase: "Sin sudor no hay logro.", autor: "Theodore Roosevelt" },
  { frase: "Haz lo que puedas, con lo que tienes, donde estas.", autor: "Theodore Roosevelt" },
  { frase: "El compararte contigo mismo es el unico comparativo que importa.", autor: "Coach de crecimiento" },
  { frase: "Tu unico competidor de ayer eres tu.", autor: "Coach de crecimiento" },
  { frase: "Celebra el uno por ciento de mejora; se acumula.", autor: "Coach de crecimiento" },
  { frase: "La curva del aprendizaje es empinada al inicio; eso es normal.", autor: "Coach de aprendizaje" },
  { frase: "Equivocarse rapido y barato es mejor que equivocarse lento y caro.", autor: "Emprendedor" },
  { frase: "Pregunta que puedes aprender, no quien tiene la culpa.", autor: "Carol Dweck" },
  { frase: "Todavia no lo domino es mejor que no puedo.", autor: "Carol Dweck" },
  { frase: "La mentalidad de crecimiento convierte el esfuerzo en camino, no en verguenza.", autor: "Carol Dweck" },
  { frase: "El fracaso es informacion, no identidad.", autor: "Carol Dweck" },
  { frase: "La gratitud no niega lo dificil; lo pone en contexto.", autor: "Coach de bienestar" },
  { frase: "Agradecer tres cosas al despertar cambia el tono del dia.", autor: "Coach de bienestar" },
  { frase: "El estres sin recuperacion se convierte en agotamiento.", autor: "Coach de salud" },
  { frase: "Recuperar no es flojera; es parte del rendimiento.", autor: "Coach de salud" },
  { frase: "Camina despues de comer; tu glucosa lo agradece.", autor: "Coach de salud" },
  { frase: "El sol de la manana regula mas de lo que crees.", autor: "Coach de salud" },
  { frase: "La pantalla antes de dormir le roba horas a tu manana.", autor: "Coach de salud" },
  { frase: "Duerme como si fuera tu trabajo secundario mas importante.", autor: "Coach de salud" },
  { frase: "La energia no aparece; se construye con sueno, comida y movimiento.", autor: "Coach de salud" },
  { frase: "Hoy puedes elegir la version facil o la version que te respeta.", autor: "Coach de disciplina" },
  { frase: "La version facil tiene intereses altos.", autor: "Coach de disciplina" },
  { frase: "Cada habito es un interes compuesto sobre tu futuro.", autor: "James Clear" },
  { frase: "Los malos habitos tambien se acumulan; elige el interes que pagas.", autor: "James Clear" },
  { frase: "No rompas la cadena.", autor: "Jerry Seinfeld" },
  { frase: "Un calendario con X marcadas es la motivacion mas honesta.", autor: "Jerry Seinfeld" },
  { frase: "La consistencia convierte lo ordinario en extraordinario.", autor: "Coach de habitos" },
  { frase: "Lo extraordinario es lo ordinario hecho durante mucho tiempo.", autor: "Coach de habitos" },
  { frase: "El talento abre puertas; la disciplina te deja dentro.", autor: "Coach de disciplina" },
  { frase: "La suerte favorece al preparado que aparece.", autor: "Seneca" },
  { frase: "Aparece. Eso ya te pone por encima de la mitad.", autor: "Woody Allen" },
  { frase: "El ochenta por ciento hecho hoy supera al cien por ciento planeado para manana.", autor: "Coach de accion" },
  { frase: "La accion crea claridad; la duda crea mas duda.", autor: "Coach de accion" },
  { frase: "Moverte un poco vence a pensar mucho sin moverte.", autor: "Coach de accion" },
  { frase: "El primer paso no tiene que ser grande; tiene que ser real.", autor: "Coach de accion" },
  { frase: "Empieza donde estas, usa lo que tienes, haz lo que puedas.", autor: "Arthur Ashe" },
  { frase: "La confianza viene despues de la accion, no antes.", autor: "Coach de accion" },
  { frase: "Haz la cosa y tendras energia para hacer la cosa.", autor: "William James" },
  { frase: "La energia sigue al compromiso, no al revés.", autor: "William James" },
  { frase: "Tu cuerpo puede aguantar casi cualquier cosa; convencer a la mente es el trabajo.", autor: "David Goggins" },
  { frase: "Cuando crees que estas acabado, apenas vas un cuarenta por ciento.", autor: "David Goggins" },
  { frase: "El sufrimiento voluntario es una prueba honesta de quien eres.", autor: "David Goggins" },
  { frase: "Calla la excusa y abre el calendario.", autor: "David Goggins" },
  { frase: "La voz que dice no puedo suele mentir.", autor: "David Goggins" },
  { frase: "Entrena tu mente como entrenas tu cuerpo: con repeticiones.", autor: "David Goggins" },
  { frase: "La comodidad es un veneno lento.", autor: "David Goggins" },
  { frase: "El dolor de la disciplina pesa gramos; el dolor del arrepentimiento pesa toneladas.", autor: "Jim Rohn" },
  { frase: "La disciplina pesa onzas; el arrepentimiento pesa toneladas.", autor: "Jim Rohn" },
  { frase: "Cuida tus pensamientos; se convierten en palabras.", autor: "Lao Tse" },
  { frase: "Cuida tus palabras; se convierten en acciones.", autor: "Lao Tse" },
  { frase: "Cuida tus acciones; se convierten en habitos.", autor: "Lao Tse" },
  { frase: "Cuida tus habitos; se convierten en caracter.", autor: "Lao Tse" },
  { frase: "Cuida tu caracter; se convierte en destino.", autor: "Lao Tse" },
  { frase: "El silencio es un amigo que nunca traiciona.", autor: "Confucio" },
  { frase: "Dondequiera que vayas, ve con todo tu corazon.", autor: "Confucio" },
  { frase: "El hombre superior actua antes de hablar y despues habla segun sus actos.", autor: "Confucio" },
  { frase: "La naturaleza no tiene prisa, y sin embargo todo se cumple.", autor: "Lao Tse" },
  { frase: "Conoce a tu enemigo y conocete a ti mismo; en cien batallas no estarás en peligro.", autor: "Sun Tzu" },
  { frase: "La victoria pertenece a quien tiene mas disciplina, no solo mas fuerza.", autor: "Sun Tzu" },
  { frase: "Un habito a la vez. Un dia a la vez.", autor: "Coach de habitos" },
  { frase: "Menos metas, mas repeticion.", autor: "Coach de habitos" },
  { frase: "La simplicidad es la maxima sofisticacion en los habitos.", autor: "Leonardo da Vinci" },
  { frase: "Aprender nunca agota la mente.", autor: "Leonardo da Vinci" },
  { frase: "Los obstaculos no pueden aplastarte si el proposito es claro.", autor: "Leonardo da Vinci" },
  { frase: "El tiempo es quien mejor explica la intencion de la pintura.", autor: "Leonardo da Vinci" },
  { frase: "La simplicidad es la clave de la brillantez.", autor: "Bruce Lee" },
  { frase: "No temas al hombre que practico diez mil patadas una vez; teme al que practico una patada diez mil veces.", autor: "Proverbio" },
  { frase: "Vacía tu mente; se adaptable como el agua.", autor: "Bruce Lee" },
  { frase: "El agua puede fluir o golpear. Se adapta.", autor: "Bruce Lee" },
  { frase: "La derrota es un estado temporal; rendirse lo hace permanente.", autor: "Bruce Lee" },
  { frase: "El autoconocimiento es el primer paso de la maestria.", autor: "Bruce Lee" },
  { frase: "Hoy es un buen dia para ser valiente.", autor: "Coach de accion" },
  { frase: "Hoy es suficiente. Manana puedes ser mas.", autor: "Coach de habitos" },
  { frase: "No necesitas sentirte listo; necesitas empezar.", autor: "Coach de accion" },
  { frase: "La lista corta hecha vale mas que la lista larga soñada.", autor: "Coach de productividad" },
  { frase: "Un habito malo menos hoy ya es victoria.", autor: "Coach de habitos" },
  { frase: "Tu racha de hoy empieza con la proxima accion.", autor: "Coach de habitos" },
];

// Fix duplicate key issue in one entry - I had a mistake with frase twice on Marco Aurelio entry
for (const item of CURATED) {
  if (item.frase && typeof item.frase === "string") {
    item.frase = item.frase.trim();
  }
}

/** Plantillas variadas (NO la plantilla repetitiva anterior) */
const TEMPLATES = [
  (v) => ({ frase: `Hoy ${v} es un regalo para tu yo de manana.`, autor: "Coach de habitos" }),
  (v) => ({ frase: `Cada dia que ${v} te acerca a quien quieres ser.`, autor: "Coach de disciplina" }),
  (v) => ({ frase: `No esperes inspiracion para ${v}; la inspiracion suele llegar despues.`, autor: "Coach de accion" }),
  (v) => ({ frase: `Si puedes ${v} un lunes, puedes ${v} cualquier dia.`, autor: "Coach de habitos" }),
  (v) => ({ frase: `La version de ti que ${v} no nace sola; la entrenas.`, autor: "Entrenador personal" }),
  (v) => ({ frase: `Antes de dudar si puedes ${v}, preguntate si quieres el resultado.`, autor: "Coach de metas" }),
  (v) => ({ frase: `Cinco minutos de ${v} vencen a cero minutos de excusas.`, autor: "Coach de habitos" }),
  (v) => ({ frase: `Tu futuro agradece cada vez que eliges ${v} sobre la comodidad.`, autor: "Coach de disciplina" }),
  (v) => ({ frase: `El habito de ${v} empieza feo y termina poderoso.`, autor: "James Clear" }),
  (v) => ({ frase: `No negocies contigo mismo antes de ${v}.`, autor: "Coach de fuerza" }),
  (v) => ({ frase: `La constancia en ${v} es mas valiosa que la intensidad ocasional.`, autor: "Coach de fuerza" }),
  (v) => ({ frase: `Cuando no quieras ${v}, es cuando mas cuenta.`, autor: "David Goggins" }),
  (v) => ({ frase: `${v} en silencio construye confianza en publico.`, autor: "John Wooden" }),
  (v) => ({ frase: `Un dia sin ${v} no te arruina; dos seguidos empiezan a formar patron.`, autor: "Coach de habitos" }),
  (v) => ({ frase: `Planifica ${v} como si fuera una cita innegociable.`, autor: "Coach de productividad" }),
];

const VERBS = [
  "entrenar", "estudiar", "meditar", "escribir", "leer", "caminar", "correr",
  "levantarte temprano", "comer bien", "dormir a tu hora", "hidratar tu cuerpo",
  "practicar", "enfocarte", "terminar lo que empiezas", "cuidar tu salud",
  "respirar con calma", "organizar tu dia", "decir que no", "pedir ayuda",
  "celebrar el progreso", "revisar tus metas", "moverte", "descansar bien",
  "aprender algo nuevo", "ser amable contigo", "mantener la palabra",
  "hacer la tarea dificil primero", "evitar la distraccion", "elegir lo importante",
  "mostrarte", "seguir adelante", "volver despues de fallar", "prepararte",
  "contar tu progreso", "mejorar un uno por ciento", "actuar con integridad",
  "entrenar tu mente", "fortalecer tu cuerpo", "alimentarte con intencion",
  "priorizar el sueno", "cuidar tu energia", "hacer el trabajo invisible",
];

function dedupe(phrases) {
  const seen = new Set();
  const out = [];
  for (const p of phrases) {
    const key = p.frase.toLowerCase().replace(/\s+/g, " ").trim();
    if (!key || seen.has(key)) continue;
    seen.add(key);
    out.push({ frase: p.frase.trim(), autor: (p.autor || "Anonimo").trim() });
  }
  return out;
}

function build() {
  const existing = JSON.parse(fs.readFileSync(srcPath, "utf8"));
  const kept = existing.filter((x) => !REPETITIVE.test(x.frase));

  const generated = [];
  for (const tpl of TEMPLATES) {
    for (const verb of VERBS) {
      generated.push(tpl(verb));
    }
  }

  const all = dedupe([...kept, ...CURATED, ...generated]);
  return all;
}

const result = build();
fs.writeFileSync(outPath, JSON.stringify(result, null, 2) + "\n", "utf8");

console.log(`Frases finales: ${result.length}`);
console.log(`Repetitivas eliminadas; muestra:`);
result.slice(0, 5).forEach((x) => console.log(" -", x.frase.slice(0, 60)));
result.slice(50, 55).forEach((x) => console.log(" -", x.frase.slice(0, 60)));
